export const accessories = [
    {
        id: 1, 
        itemname: 'necklace',  
        color: 'gold', 
        size: '16in', 
        gender: 'men', 
        forkids: true, 
        details: 'Description content', 
        cost: '$200', 
        img: 'image link/url goes here',
    },
    {
        id: 2, 
        itemname: 'ring', 
        color: 'rose gold', 
        size: '7mm', 
        gender: 'women', 
        forkids: false, 
        details: 'Description content', 
        cost: '$1000', 
        img: 'image link/url goes here',
    },
    {
        id: 3, 
        itemname: 'watch',  
        color: 'silver', 
        size: '40mm', 
        gender: 'men', 
        forkids: false, 
        details: 'Description content', 
        cost: '$500', 
        img: 'image link/url goes here',
    }
];