const products = [
    // TOPS *********************************************************************************************
    // MEN
    {
        name: 'Tech Fleece Windrunner',
        color: 'lime green',
        size: 'med',
        gender: 'men',
        forkids: false,
        details: "Embrace the elements with this iconic jacket, featuring a sleek design and wind-resistant technology. Elevate your outerwear game with Nike's signature blend of sporty flair and weather-ready performance.",
        cost: 165,
        img: 'https://shorturl.at/eKN38',
        category: 'tops'
    },
    {
        name: 'City-S Fleece Windrunner',
        color: 'black',
        size: 'med',
        gender: 'men',
        forkids: false,
        details: "Where city style meets practicality. Navigate the streets with confidence in this sleek jacket, blending urban aesthetics with wind-resistant technology. Elevate your outerwear with Nike's iconic urban-inspired design, perfect for both style and functionality.",
        cost: 150,
        img: 'https://shorturl.at/egAL9',
        category: 'tops'
    },
    {
        name: 'Sno-W Mountain Windrunner',
        color: 'white',
        size: 'large',
        gender: 'men',
        forkids: false,
        details: "A timeless blend of style and functionality. Elevate your look with this crisp and classic white jacket, designed to keep you both stylish and protected from the elements. Embrace the iconic Nike touch in a versatile windbreaker perfect for any occasion.",
        cost: 200,
        img: 'https://shorturl.at/tLN01',
        category: 'tops'
    },
    {
        name: 'Iconic Puff Jacket',
        color: 'grey',
        size: 'med',
        gender: 'men',
        forkids: false,
        details: "Your cozy companion for chilly days. Elevate your warmth and style with this comfortable and trendy puffer jacket. Stay snug and on-trend in any weather with the Nike Puff Jacket",
        cost: 210,
        img: 'https://shorturl.at/bgGK1',
        category: 'tops'
    },
    {
        name: 'Navy Puffer Vest',
        color: 'navy blue',
        size: 'med',
        gender: 'men',
        forkids: false,
        details: "A sleek and versatile addition to your wardrobe. Elevate your style with this lightweight yet cozy vest, perfect for layering and staying on-trend.",
        cost: 155,
        img: 'https://shorturl.at/bvA79',
        category: 'tops'
    },
    {
        name: 'Casual Classic Hoodie',
        color: 'grey',
        size: 'large',
        gender: 'men',
        forkids: false,
        details: "A must-have for casual comfort and style. Elevate your laid-back look with this classic hoodie, featuring the iconic Nike logo. Stay cozy and on-trend.",
        cost: 120,
        img: 'https://rb.gy/4ev845',
        category: 'tops'
    },
    {
        name: 'Dotty-Dot Hoodie',
        color: 'white/black print',
        size: 'med',
        gender: 'men',
        forkids: false,
        details: "A stylish twist on casual comfort. Embrace a laid-back, yet stylish look with this hoodie featuring a trendy spot design",
        cost: 200,
        img: 'https://rb.gy/klbes5',
        category: 'tops'
    },
    {
        name: 'Chill-N Hoodie',
        color: 'white',
        size: 'med',
        gender: 'men',
        forkids: false,
        details: "A timeless essential for a clean, crisp and stylish look. Enhance your casual comfort with this classic white hoodie",
        cost: 140,
        img: 'http://tiny.cc/xt9ivz',
        category: 'tops'
    },
    {
        name: 'Edge-E Urban Hoodie',
        color: 'black',
        size: 'large',
        gender: 'men',
        forkids: false,
        details: "A fashion-forward choice for cozy style. Elevate your look with this hoodie featuring a unique print design, adding a touch of trendiness to your casual wardrobe. Stay effortlessly cool and comfortable with Nike.",
        cost: 150,
        img: 'http://tiny.cc/ut9ivz',
        category: 'tops'
    },
    {
        name: 'Day-Night Sweater',
        color: 'white',
        size: 'med',
        gender: 'men',
        forkids: false,
        details: "A timeless staple for clean and versatile style. Elevate your casual comfort with this classic white sweater, perfect for effortlessly staying on-trend. Embrace simplicity and sophistication in white",
        cost: 80,
        img: 'http://tiny.cc/qt9ivz',
        category: 'tops'
    },
    {
        name: 'Casual Long-Sleeve',
        color: 'beige',
        size: 'med',
        gender: 'men',
        forkids: false,
        details: "A versatile essential for cultivating style with ease. Enhance your comfort with this classic long sleeve in a chic beige hue, offering a timeless and on-trend addition to your wardrobe. Embrace simplicity and warmth.",
        cost: 70,
        img: 'https://t.ly/ACZZa',
        category: 'tops'
    },
    {
        name: 'Album Long-Sleeve',
        color: 'white',
        size: 'large',
        gender: 'men',
        forkids: false,
        details: "A versatile essential for cultivating style with ease. Enhance your comfort with this classic long sleeve in a crisp white hue, offering a timeless and on-trend addition to your wardrobe. Embrace the simplicity and freshness of white.",
        cost: 55,
        img: 'https://shorturl.at/kpAV6',
        category: 'tops'
    },
    {
        name: 'Blackout T-Shirt',
        color: 'black',
        size: 'med',
        gender: 'men',
        forkids: false,
        details: "A sleek essential for cultivating style effortlessly. Elevate your comfort with this classic tee in a timeless black hue, offering a versatile and on-trend addition to your wardrobe.",
        cost: 45,
        img: 'http://tiny.cc/7u9ivz',
        category: 'tops'
    },
    {
        name: 'Solaris T-Shirt',
        color: 'yellow',
        size: 'med',
        gender: 'men',
        forkids: false,
        details: "A vibrant essential for cultivating style with ease. Enhance your comfort with this classic tee in a lively yellow hue, offering a cheerful and on-trend addition to your wardrobe.",
        cost: 35,
        img: 'http://tiny.cc/1u9ivz',
        category: 'tops'
    },
    {
        name: 'Elegantia T-Shirt',
        color: 'black',
        size: 'large',
        gender: 'men',
        forkids: false,
        details: "An easygoing choice to freshen up your style effortlessly. Revel in the comfort of this classic tee, boasting a chic beige shade that brings a contemporary touch to your wardrobe. Embrace the laid-back charm and warmth.",
        cost: 60,
        img: 'http://tiny.cc/eu9ivz',
        category: 'tops'
    },
    // KIDS (MEN)
    {
        name: 'Culture T-Shirt',
        color: 'black',
        size: 'small',
        gender: 'men',
        forkids: true,
        details: "Pregame warm-ups, playing with friends after school or watching your team win over the weekend, this Culture of Basketball top does it all.",
        cost: 60,
        img: 'https://rebrand.ly/rire0yg',
        category: 'tops'
    },
    {
        name: 'Dry-FIT Long-Sleeve',
        color: 'blue',
        size: 'med',
        gender: 'men',
        forkids: true,
        details: "Time to stock up your drawer with active tops! Whether you're practicing, in school or just having fun, the fabric is breathable, plus sweat won't get in the way, so playtime never stops.",
        cost: 30,
        img: 'https://rebrand.ly/pa27elm',
        category: 'tops'
    },
    {
        name: 'Tech Fleece Jacket',
        color: 'beige/white',
        size: 'large',
        gender: 'men',
        forkids: true,
        details: "Why should parents have all the fun? We've updated this collection to match your parents' Tech Fleece so you can rock what they wear (or what they wish they had). Our premium, lightweight fleece, both inside and out gives you plenty of warmth without adding bulk.",
        cost: 110,
        img: 'https://rebrand.ly/zokhaiw',
        category: 'tops'
    },
    //WOMENS
    {
        name: 'Chill Terry Hoodie',
        color: 'white',
        size: 'small',
        gender: 'women',
        forkids: false,
        details: "Grounded in style, comfort and versatility, meet our take on luxury loungewear. Perfect for warmer days, swap out your fleecy hoodie for this soft, light layer with a loose fit. It's cozy enough to wear around the house yet elevated enough to wear out in the city.",
        cost: 75,
        img: 'https://shorturl.at/mrzGJ',
        category: 'tops'
    },
    {
        name: 'Phoenix Fleece Hoodie',
        color: 'lime green',
        size: 'med',
        gender: 'women',
        forkids: false,
        details: "Grounded in style, comfort and versatility, meet our take on luxury loungewear. This classic hoodie helps you stay cozy all day long, thanks to midweight fleece that feels soft yet structured. Plus, exaggerated details (like taller ribbing and oversized fit) give you a trend-right look.",
        cost: 60,
        img: 'https://shorturl.at/hlmwA',
        category: 'tops'
    },
    {
        name: 'Long Fleece Hoodie',
        color: 'white',
        size: 'small',
        gender: 'women',
        forkids: false,
        details: "Rise up and transform your fleece wardrobe with strong cozy vibes. All about warmth and comfort, the longer cut of this full-zip hoodie lets you bring the snuggly feeling of your favorite throw blanket with you everywhere you go.",
        cost: 85,
        img: 'https://shorturl.at/hpHIP',
        category: 'tops'
    },
    {
        name: 'Asem Tech Fleece Hoodie',
        color: 'white',
        size: 'large',
        gender: 'women',
        forkids: false,
        details: "A modern silhouette and a color palette inspired by natural minerals. Our premium, lightweight fleece is smooth both inside and out—giving you plenty of warmth without unnecessary bulk. Complete your look with matching joggers or your favorite pair of leggings.",
        cost: 70,
        img: 'https://shorturl.at/nDV16',
        category: 'tops'
    },
    {
        name: 'Cropped Phoenix Long-Sleeve',
        color: 'black',
        size: 'med',
        gender: 'women',
        forkids: false,
        details: "Grounded in style, comfort and versatility, meet our take on luxury loungewear. This mock-neck top is made with textured fleece that feels cozy enough to wear around the house yet elevated enough to wear out in the city.",
        cost: 60,
        img: 'https://shorturl.at/xDELN',
        category: 'tops'
    },
    {
        name: 'Light Crew Sweatshirt',
        color: 'pink',
        size: 'large',
        gender: 'women',
        forkids: false,
        details: "Meet your new favorite sweatshirt. The one you pull out of the dirty clothes pile because its too good not to wear one more time. (No one’s gonna know.) Super soft with a slightly oversized fit and extra volume in the sleeves, it's easy to pull on and perfect for layering.",
        cost: 90,
        img: 'https://rb.gy/z5z165',
        category: 'tops'
    },
    {
        name: 'FlyOut V-Neck Sweatshirt',
        color: 'light beige',
        size: 'med',
        gender: 'women',
        forkids: false,
        details: "Rise up and transform your fleece wardrobe with comfy vibes. The oversized fit and double V neckline ensure your look is anything but basic. Our midweight brushed fleece feels extra soft on the inside and smooth on the outside, helping you stay cozy while keeping its structured shape.",
        cost: 75,
        img: 'https://rb.gy/slpw27',
        category: 'tops'
    },
    {
        name: 'Phoenix V-neck Long-Sleeve',
        color: 'white',
        size: 'small',
        gender: 'women',
        forkids: false,
        details: "Grounded in style, comfort and versatility, meet our take on luxury loungewear. Dropped shoulder seams create a relaxed look, while midweight fleece makes this V-neck top cozy enough to wear around the house yet elevated enough to wear out in the city.",
        cost: 60,
        img: 'https://rebrand.ly/c6ah5sx',
        category: 'tops'
    },
    {
        name: 'Icy Long-Sleeve Crop Top',
        color: 'icy blue',
        size: 'small',
        gender: 'women',
        forkids: false,
        details: "From checking off your to-do list to sweating in the studio, you can feel comfortable through it all in this snug, stretchy top. As part of the Nike Luxe line, it defines luxury with ultrasoft, smooth fabric that breathes to help keep you dry and cool. Thumbholes hold your sleeves in place so you're ready for whatever activity comes next.",
        cost: 50,
        img: 'https://rebrand.ly/cdzsjtt',
        category: 'tops'
    },
    {
        name: 'Sporty Tank Top',
        color: 'brown',
        size: 'large',
        gender: 'women',
        forkids: false,
        details: "Grounded in style, comfort and versatility, meet our new luxury loungewear. With a cropped fit that hits near the waist, this tank is made from our soft mini-ribbed jersey is stretchy with a slight drape, making it perfect for everyday wear. So wear it around the clock and all through the calendar.",
        cost: 35,
        img: 'https://rebrand.ly/04m1lfi',
        category: 'tops'
    },
    {
        name: 'Cropped Cutesy Tank Top',
        color: 'white',
        size: 'med',
        gender: 'women',
        forkids: false,
        details: "From checking off your to-do list to sweating in the studio, you can feel comfortable through it all in this snug, stretchy tank top. As part of the Nike Luxe line, it defines luxury with ultrasoft, smooth fabric that breathes to help keep you dry and cool. Racerback straps and a back cutout help keep the air flowing through high-heat areas.",
        cost: 60,
        img: 'https://rebrand.ly/y02n6np',
        category: 'tops'
    },
    {
        name: 'Fluffy Puffer Jacket',
        color: 'brown',
        size: 'large',
        gender: 'women',
        forkids: false,
        details: "This loose puffer is made for those frigid days and colder nights. Extra coziness comes from the Thermore® Ecodown® fill and Nike Therma-FIT technology that helps manage your natural body heat to keep you warm. Bungees at the hem, plenty of pockets and a hood work together to help shield you from wind and rain.",
        cost: 200,
        img: 'https://rebrand.ly/773el9j',
        category: 'tops'
    },
    {
        name: 'Swoosh-Prima Puffer Jacket',
        color: 'white',
        size: 'small',
        gender: 'women',
        forkids: false,
        details: "Stay warm on the coldest days by bundling up in this oversized puffer. Nike Therma-FIT technology helps manage your bodys natural heat to help keep you warm in cold-weather conditions.",
        cost: 220,
        img: 'https://rebrand.ly/0s0ur1k',
        category: 'tops'
    },
    {
        name: 'Padded Sports Bra',
        color: 'black',
        size: 'med',
        gender: 'women',
        forkids: false,
        details: "Who said you couldn't be stylish while you kick butt at the gym? For the fashionistas who want to train—and look good while they do it—this bandeau sports bra will soon be a staple in your closet. Customizable padding and straps let you change up your look and support while sweat-wicking fabric helps you feel ready for anything your day throws at you.",
        cost: 50,
        img: 'https://rebrand.ly/rh7b0ww',
        category: 'tops'
    },
    {
        name: 'Swoosh Sports Bra',
        color: 'navy blue',
        size: 'large',
        gender: 'women',
        forkids: false,
        details: "You're on the move. Your padding shouldn't be. This Swoosh bra's sewn-in pads stay in place so you can work hard without worrying about them shifting or folding. Great for training workouts and dance classes, medium support gives you a snug hold that helps keep everything in place.",
        cost: 55,
        img: 'https://rebrand.ly/v14gx2v',
        category: 'tops'
    },
        // KIDS (WOMEN)
        {
            name: 'Club Love T-Shirt',
            color: 'white',
            size: 'small',
            gender: 'women',
            forkids: true,
            details: "Made with our soft and lightweight everyday cotton fabric, this roomy tee pairs perfectly with every sneaker in your collection. So go ahead and rock your favorite pair.",
            cost: 25,
            img: 'http://tiny.cc/yz9ivz',
            category: 'tops'
        },
        {
            name: 'Lil` Long-Sleeve',
            color: 'light grey',
            size: 'med',
            gender: 'women',
            forkids: true,
            details: "Smooth on the outside, brushed soft on the inside, this lightweight fleece is an easy layer when you want a little extra warmth.",
            cost: 30,
            img: 'https://shorturl.at/gnFOR',
            category: 'tops'
        },
        {
            name: 'Play-G Fleece Hoodie',
            color: 'beige',
            size: 'large',
            gender: 'women',
            forkids: true,
            details: "Cold weather doesn't stand a chance against you and your Tech Fleece. Our premium, lightweight fleece both inside and out gives you plenty of warmth without adding bulk.",
            cost: 105,
            img: 'https://shorturl.at/uvHR8',
            category: 'tops'
        },

    // BOTTOMS *********************************************************************************************
    // MEN
    {
        name: 'Coze-E Joggers',
        color: 'grey',
        size: '34',
        gender: 'men',
        forkids: false,
        details: "The perfect fusion of comfort and style. Elevate your casual wardrobe with these iconic joggers, designed for a cozy fit and a sleek, sporty look. Whether you're hitting the gym or relaxing at home, stay on trend with Nike Joggers.",
        cost: 40,
        img: 'https://shorturl.at/nopI2',
        category: 'bottoms'
    },
    {
        name: 'Sport-E Joggers',
        color: 'light grey',
        size: '34',
        gender: 'men',
        forkids: false,
        details: "Where comfort meets contemporary cool. These iconic joggers redefine casual style with a perfect balance of comfort and urban flair. Whether you're on the move or chilling out, stay cozy with these Nike Joggers.",
        cost: 40,
        img: 'https://shorturl.at/kwHS0',
        category: 'bottoms'
    },
    {
        name: 'Urban-E Joggers',
        color: 'black',
        size: '34',
        gender: 'men',
        forkids: false,
        details: "Comfort meets trendsetting style. Upgrade your casual attire with these iconic joggers, crafted for a snug fit and a modern, athletic vibe. Whether you're active or taking it easy, stay effortlessly stylish.",
        cost: 50,
        img: 'https://shorturl.at/IS134',
        category: 'bottoms'
    },
    {
        name: 'Snow-E Joggers',
        color: 'white',
        size: '34',
        gender: 'men',
        forkids: false,
        details: "A pristine blend of comfort and style. Embrace the pure, crisp look with these iconic joggers, tailored for a cozy fit and a winter-inspired vibe. Perfect for a cool and relaxed aesthetic.",
        cost: 45,
        img: 'https://t.ly/rWhnT',
        category: 'bottoms'
    },
    {
        name: 'Sporty Urban Shorts',
        color: 'black',
        size: '34',
        gender: 'men',
        forkids: false,
        details: "The epitome of comfort and style. Elevate your casual wardrobe with these iconic shorts, designed for a relaxed fit and a sporty edge. Whether you're hitting the gym or enjoying a laid-back day, stay on point with these Nike Shorts.",
        cost: 35,
        img: 'https://shorturl.at/deiIU',
        category: 'bottoms'
    },
    {
        name: 'All-Speed Shorts',
        color: 'black',
        size: '34',
        gender: 'men',
        forkids: false,
        details: "The perfect fusion of comfort and performance. Designed for your stride, these iconic shorts provide a light and breathable fit, ensuring you stay cool and stylish on every run. Elevate your running experience with Nike's blend of comfort and athletic style.",
        cost: 30,
        img: 'https://t.ly/c9XlK',
        category: 'bottoms'
    },
    {
        name: 'Beast Mode Shorts',
        color: 'white',
        size: '34',
        gender: 'men',
        forkids: false,
        details: "Where comfort meets fashion. These iconic shorts are crafted for a chic, on-trend look, providing both style and ease for any occasion.",
        cost: 45,
        img: 'https://t.ly/QpgmS',
        category: 'bottoms'
    },
    {
        name: 'Hooper Shorts',
        color: 'navy blue',
        size: '34',
        gender: 'men',
        forkids: false,
        details: "The perfect blend of comfort and court-ready style. These classic shorts are designed for optimal performance on the basketball court, providing a comfortable fit and a sleek, athletic look. Elevate your game for both functionality and sporty flair.",
        cost: 35,
        img: 'https://t.ly/xHnfo',
        category: 'bottoms'
    },
    {
        name: 'Everyday Versatile Pants',
        color: 'dirty green',
        size: '34',
        gender: 'men',
        forkids: false,
        details: "Your go-to for a seamless blend of comfort and style. Whether you're hitting the gym or navigating your day, these pants offer a versatile fit with a touch of sporty sophistication. Elevate your wardrobe with this perfect fit, crafted for all occasions.",
        cost: 50,
        img: 'https://t.ly/2OAWt',
        category: 'bottoms'
    },
    {
        name: 'Blissful Fleece Pants',
        color: 'red',
        size: '34',
        gender: 'men',
        forkids: false,
        details: "Your cozy essential for ultimate comfort. Embrace warmth and style with these soft fleece pants, perfect for lounging or staying active on cooler days.",
        cost: 80,
        img: 'https://t.ly/SEqit',
        category: 'bottoms'
    },
    {
        name: 'Crystal-C Cargos',
        color: 'light blue',
        size: '34',
        gender: 'men',
        forkids: false,
        details: "The perfect blend of functionality and urban style. Elevate your wardrobe with these versatile pants, designed for practicality with a touch of athletic edge. Whether you're on the move or embracing a casual day, these cargo pants offer a comfortable and trendy solution for any adventure.",
        cost: 100,
        img: 'http://tiny.cc/n9aivz',
        category: 'bottoms'
    },
    {
        name: 'Cream-C Cargos',
        color: 'light cream',
        size: '34',
        gender: 'men',
        forkids: false,
        details: "Where versatility meets urban elegance. Elevate your style with these chic and functional pants, blending practicality with a touch of sophistication in a trendy cream hue. Whether you're on the go or enjoying a laid-back day, these cargo pants bring comfort and style together seamlessly.",
        cost: 120,
        img: 'https://shorturl.at/abtAO',
        category: 'bottoms'
    },
    {
        name: 'Classic Boxers',
        color: 'black',
        size: '34',
        gender: 'men',
        forkids: false,
        details: "Where style meets essential support. Embrace a perfect fit and a hint of athletic flair with these must-have undergarments.",
        cost: 20,
        img: 'https://t.ly/8e7D4',
        category: 'bottoms'
    },
    {
        name: 'Icy Cool Boxers',
        color: 'blue',
        size: '34',
        gender: 'men',
        forkids: false,
        details: "Where comfort meets performance. Experience all-day ease with these essential undergarments, designed to provide a snug fit and the iconic Nike touch. Elevate your daily comfort with this perfect choice for a confident foundation.",
        cost: 25,
        img: 'https://shorturl.at/hmpBQ',
        category: 'bottoms'
    },
    {
        name: 'Urban-Print Boxers',
        color: 'black',
        size: '34',
        gender: 'men',
        forkids: false,
        details: "Urban style meets essential comfort. Elevate your underwear game with these trendy, printed boxers that offer a perfect fit and a touch of city-inspired flair. Make a statement in comfort and style.",
        cost: 35,
        img: 'https://t.ly/jHze4',
        category: 'bottoms'
    },
    // KIDS (MEN)
    {
        name: 'Urban Fleece Joggers',
        color: 'black',
        size: '11',
        gender: 'men',
        forkids: true,
        details: "These joggers are made of soft fleece fabric for lightweight warmth. The stretch waistband helps kiddos get a comfy fit, pockets provide spots to hold small items and the tapered leg promotes freedom of play.",
        cost: 35,
        img: 'http://tiny.cc/k1aivz',
        category: 'bottoms'
    },
    {
        name: 'Repel Training Pants',
        color: 'red',
        size: '11',
        gender: 'men',
        forkids: true,
        details: "Congrats and welcome to our gym club, Nike Athletics! We're ready to issue your gear as our new member. Inspired by throwback gym clothes designs, rep the club name on the side of these pants.",
        cost: 50,
        img: 'http://tiny.cc/p1aivz',
        category: 'bottoms'
    },
    {
        name: 'Sporty Kid Shorts',
        color: 'grey',
        size: '11',
        gender: 'men',
        forkids: true,
        details: "Little athletes can practice in style with these shorts, made of breathable mesh knit fabric in a comfy, relaxed fit for freedom of movement.",
        cost: 35,
        img: 'http://tiny.cc/u1aivz',
        category: 'bottoms'
    },

    //WOMEN
        {
            name: 'Coze-E Womens Joggers',
            color: 'black',
            size: '34',
            gender: 'women',
            forkids: false,
            details: "A perfect blend of style and comfort. Elevate your casual chic with these iconic joggers, tailored for a cozy fit and on-trend femininity.",
            cost: 40,
            img: 'http://bit.ly/3v4IBhJ',
            category: 'bottoms'
        },
        {
            name: 'Sport-E Womens Joggers',
            color: 'pink',
            size: '34',
            gender: 'women',
            forkids: false,
            details: "Where comfort meets contemporary cool. These iconic joggers redefine casual style with a perfect balance of comfort and urban flair. Whether you're on the move or chilling out, stay cozy with these Nike Joggers.",
            cost: 35,
            img: 'https://swoo.sh/3uSMMxb',
            category: 'bottoms'
        },
        {
            name: 'Urban-E Womens Joggers',
            color: 'black',
            size: '34',
            gender: 'women',
            forkids: false,
            details: "Comfort meets trendsetting style. Upgrade your casual attire with these iconic joggers, crafted for a snug fit and a modern, athletic vibe. Whether you're active or taking it easy, stay effortlessly stylish.",
            cost: 50,
            img: 'https://swoo.sh/3Nq6QgC',
            category: 'bottoms'
        },
        {
            name: 'Snow-E Womens Joggers',
            color: 'white',
            size: '34',
            gender: 'women',
            forkids: false,
            details: "A pristine blend of comfort and style. Embrace the pure, crisp look with these iconic joggers, tailored for a cozy fit and a winter-inspired vibe. Perfect for a cool and relaxed aesthetic.",
            cost: 45,
            img: 'https://swoo.sh/3Rnh6rc',
            category: 'bottoms'
        },
        {
            name: 'Sporty Womens Shorts',
            color: 'black',
            size: '34',
            gender: 'women',
            forkids: false,
            details: "The epitome of comfort and style. Elevate your casual wardrobe with these iconic shorts, designed for a relaxed fit and a sporty edge. Whether you're hitting the gym or enjoying a laid-back day, stay on point with these Nike Shorts.",
            cost: 35,
            img: 'https://swoo.sh/41hALxr',
            category: 'bottoms'
        },
        {
            name: 'Loose Fit Shorts',
            color: 'light cream',
            size: '34',
            gender: 'women',
            forkids: false,
            details: "The perfect fusion of comfort and performance. Designed for your stride, these iconic shorts provide a light and breathable fit, ensuring you stay cool and stylish on every run. Elevate your running experience with Nike's blend of comfort and athletic style.",
            cost: 30,
            img: 'https://bit.ly/3RnITYR',
            category: 'bottoms'
        },
        {
            name: 'Beast Mode Womens Shorts',
            color: 'white',
            size: '34',
            gender: 'women',
            forkids: false,
            details: "Where comfort meets fashion. These iconic shorts are crafted for a chic, on-trend look, providing both style and ease for any occasion.",
            cost: 50,
            img: 'https://bit.ly/3tlHxpd',
            category: 'bottoms'
        },
        {
            name: 'Womens Hooper Shorts',
            color: 'light pink',
            size: '34',
            gender: 'women',
            forkids: false,
            details: "The perfect blend of comfort and court-ready style. These classic shorts are designed for optimal performance on the basketball court, providing a comfortable fit and a sleek, athletic look. Elevate your game for both functionality and sporty flair.",
            cost: 35,
            img: 'https://bit.ly/47SoB0h',
            category: 'bottoms'
        },
        {
            name: 'Everyday Versatile Pants',
            color: 'black',
            size: '34',
            gender: 'women',
            forkids: false,
            details: "Push yourself forward with the right balance of support and comfort with our Nike Go leggings. Squat-proof—even during your toughest workouts—their sleek, midweight InfinaLock fabric feels compressive and supportive in all the right places. Multiple pockets let you carry everything you could need, whether you're hitting the trail, the gym or the mat.",
            cost: 50,
            img: 'https://bit.ly/47UZ46X',
            category: 'bottoms'
        },
        {
            name: 'Blissful Yoga Pants',
            color: 'dark teal',
            size: '34',
            gender: 'women',
            forkids: false,
            details: "Our Nike Universa leggings help smooth and lift, stretching freely with your every move. Wherever your workout takes you, their squat-proof, midweight InfinaSmooth fabric gives you uncompromising comfort and feels cool and sleek to the touch.",
            cost: 80,
            img: 'https://bit.ly/3REylFO',
            category: 'bottoms'
        },
        {
            name: 'Stretch-E Yoga Pants',
            color: 'light blue',
            size: '34',
            gender: 'women',
            forkids: false,
            details: "Push yourself on cold days with the right balance of support, comfort and warmth with our Nike Go leggings. Squat-proof—even during your toughest workouts—their sleek, midweight InfinaLock fabric feels compressive and supportive in all the right places.",
            cost: 45,
            img: 'https://swoo.sh/3Rj1c19',
            category: 'bottoms'
        },
        {
            name: 'Outdoor Goddess Leggings',
            color: 'baby blue',
            size: '34',
            gender: 'women',
            forkids: false,
            details: "Up for a workout or down to chill, these cozy, heat-regulating leggings are ready for whatever you are. Whether you’re hitting the trails or running errands, the soft, stretchy fabric and multiple pockets help keep you comfortable and prepared. Plus, they're thick enough to keep you covered, so you can stay confident in your deepest bend.",
            cost: 45,
            img: 'https://bit.ly/3REpqEh',
            category: 'bottoms'
        },
        {
            name: 'Flash-X Workout Leggings',
            color: 'red',
            size: '34',
            gender: 'women',
            forkids: false,
            details: "Powered by our sweat-wicking technology, these Nike Pro leggings work to keep you dry and comfortable while you push through the intensity of your toughest workouts. Soft, stretchy spandex hugs your body for gentle support.",
            cost: 60,
            img: 'https://shorturl.at/dDPRV',
            category: 'bottoms'
        },
        {
            name: 'Fast-R Soccer Pants',
            color: 'white',
            size: '34',
            gender: 'women',
            forkids: false,
            details: "Heading to early morning practice or warming up before the match, these breathable soccer pants are designed with tech to help keep you cool and dry as you work up a sweat. With mesh panels down the legs and an elastic waistband, you can stay comfortable however you choose to play.",
            cost: 65,
            img: 'https://shorturl.at/oCM12',
            category: 'bottoms'
        },
        {
            name: 'Urban Fashion Pants',
            color: 'black',
            size: '34',
            gender: 'women',
            forkids: false,
            details: "Soft but strong, these wide-leg pants are ready to keep you comfy and ready for anything throughout your packed day. Their cotton-blend ripstop fabric is sturdy but still light enough to wear in warm weather.",
            cost: 35,
            img: 'https://shorturl.at/byCN8',
            category: 'bottoms'
        },
        // KIDS (WOMEN)
        {
            name: 'Urban Girl Joggers',
            color: 'grey',
            size: '10',
            gender: 'women',
            forkids: true,
            details: "Run through chilly days in these relaxed, wide-leg pants that give you the space you need to feel ready to play.",
            cost: 35,
            img: 'https://shorturl.at/twHN1',
            category: 'bottoms'
        },
        {
            name: 'Thermal Leggings',
            color: 'black',
            size: '10',
            gender: 'women',
            forkids: true,
            details: "Brrrrr, it's too cold to go outside and play… Wait a second, what are these? Incredibly warm and snuggly leggings made with a thick fabric that's perfect for playing in cold weather? That's right!",
            cost: 35,
            img: 'https://shorturl.at/cdetF',
            category: 'bottoms'
        },
        {
            name: 'Girly Girl Shorts',
            color: 'pink',
            size: '10',
            gender: 'women',
            forkids: true,
            details: "The Nike Shorts are everything kiddos want—soft, lightweight and super comfy.",
            cost: 25,
            img: 'http://tiny.cc/92aivz',
            category: 'bottoms'
        },

    // SHOES *********************************************************************************************
    // MEN
    {
        name: 'AF 1',
        color: 'white',
        size: '12',
        gender: 'men',
        forkids: true,
        details: "The radiance lives on in the Nike Air Force 1 07, the b-ball OG that puts a fresh spin on what you know best: durably stitched overlays, clean finishes and the perfect amount of flash to make you shine.",
        cost: 115,
        img: 'https://t.ly/JaEot',
        category: 'shoes'
    },
    {
        name: 'Winterized Jordan 8',
        color: 'black/gunsmoke',
        size: '10',
        gender: 'men',
        forkids: false,
        details: "Your cold-weather kicks have arrived. This AJ8 is designed with luxe leather, reflective elements and premium suede for durable style you can put to the test. Black and Gunsmoke pair with Metallic Silver for sleek seasonal style. It's an icy look that feels cool, whether it's winter or not.",
        cost: 180,
        img: 'https://t.ly/M2Ncv',
        category: 'shoes'
    },
    {
        name: 'Vaporfly 3',
        color: 'black/white',
        size: '11',
        gender: 'men',
        forkids: false,
        details: "Giving you race-day speed to conquer any distance, the Nike Vaporfly 3 is made for the chasers, the racers, the elevated pacers who cant turn down the thrill of the pursuit. From elite runners to those new to racing, this versatile road-racing workhorse is for those who see speed as a gateway to more miles and more seemingly uncatchable highs.",
        cost: 300,
        img: 'https://t.ly/BRYJJ',
        category: 'shoes'
    },
    {
        name: 'Urban Dunk High Retros',
        color: 'black/white',
        size: '12',
        gender: 'men',
        forkids: true,
        details: "Created for the hardwood but taken to the streets, the '80s b-ball icon returns with perfectly sheened overlays and original university colors. With its classic hoops design, the Nike Dunk High Retro channels '80s vintage back onto the streets while its padded, high-top collar adds an old-school look rooted in comfort.",
        cost: 130,
        img: 'https://t.ly/4EPbo',
        category: 'shoes'
    },
    {
        name: 'Dunk High Retros SE',
        color: 'brown/beige',
        size: '10',
        gender: 'men',
        forkids: false,
        details: "The '80s b-ball icon returns with mixed materials and a neutral palette. With its classic hoops design, the Dunk High Retro channels old-school style back onto the streets, while its padded, high-top collar keeps you comfortable all day long.",
        cost: 120,
        img: 'https://t.ly/eUGqf',
        category: 'shoes'
    },
    {
        name: 'Classic Slides',
        color: 'black',
        size: '11',
        gender: 'men',
        forkids: false,
        details: "From the beach to the bleachers, the Victori One is a must-have slide for everyday activities. Subtle yet substantial updates like a wider strap and softer foam make lounging easy. Go ahead—enjoy endless comfort for your feet.",
        cost: 35,
        img: 'https://t.ly/9OZme',
        category: 'shoes'
    },
    //KIDS (MEN)
    {
        name: 'Flight Jordans',
        color: 'white/red/black',
        size: '7',
        gender: 'men',
        forkids: true,
        details: "A sneaker that brings a classic performance look to streetwear. It features premium leather structured around an internal sleeve for a secure fit that's easy to get on and off.",
        cost: 100,
        img: 'https://shorturl.at/uQRS6',
        category: 'shoes'
    },
    {
        name: 'Dunk Lows',
        color: 'white/grey',
        size: '7',
        gender: 'men',
        forkids: true,
        details: "Created for the hardwood but taken to the streets, this 80s basketball icon returns with smooth matte finished overlays and original flair.",
        cost: 100,
        img: 'http://tiny.cc/64aivz',
        category: 'shoes'
    },
    {
        name: 'Jumper-Xs',
        color: 'white/black',
        size: '7',
        gender: 'men',
        forkids: true,
        details: "Bring your kiddo into the Jordan family with kicks celebrating MJ's first 3 championships. Sturdy materials add support, and an extra-large opening makes it easier to take 'em on and off little feet.",
        cost: 80,
        img: 'http://tiny.cc/g4aivz',
        category: 'shoes'
    },
    {
        name: 'Frozen Low 1',
        color: 'white/ice blue',
        size: '7',
        gender: 'men',
        forkids: true,
        details: "Where's that cool breeze coming from? Oh, it's you in these icy AJ1s! These season-ready kicks come with a bevy of wintery details: iced clear outsole, 'frozen' textured leather overlays, and that glitter-filled Swoosh inspired by a swirling snow globe. Shake up your winter look.",
        cost: 100,
        img: 'http://tiny.cc/k7aivz',
        category: 'shoes'
    },

    // WOMEN
    {
        name: 'Court Vision Lows',
        color: 'white/light pink',
        size: '9',
        gender: 'women',
        forkids: false,
        details: "Meet the Nike Court Vision Low Next Nature. Made from at least 20% recycled materials by weight, its crisp upper and stitched overlays are inspired by the days of hook-shots and tube socks.",
        cost: 120,
        img: 'https://rebrand.ly/bmf00h6',
        category: 'shoes'
    },
    {
        name: 'AF 1 Shadow',
        color: 'white/pink/bright yellow',
        size: '9',
        gender: 'women',
        forkids: false,
        details: "Everything you love about the AF1—but doubled! The Nike Air Force 1 Shadow puts a playful twist on a hoops icon to highlight the best of AF1 DNA. Layered overlays bring added depth while doubled branding and an exaggerated midsole help give these sneakers a bold look. Vibrant colors provide an energetic look for 2 times the style.",
        cost: 150,
        img: 'https://rebrand.ly/f2xc0us',
        category: 'shoes'
    },
    {
        name: 'Dunk Low Twists',
        color: 'black',
        size: '9',
        gender: 'women',
        forkids: false,
        details: "The '80s b-ball icon returns with classic details and throwback hoops flair. Channeling vintage style back onto the streets, its padded collar and extra-puffy silhouette let you take your game anywhere—in comfort.",
        cost: 110,
        img: 'https://rebrand.ly/j35ddgh',
        category: 'shoes'
    },
    {
        name: 'MC Trainers',
        color: 'black/white',
        size: '9',
        gender: 'women',
        forkids: false,
        details: "The Nike MC Trainer 2 can help you shift from circuit training in the weight room to the field turf for quick-twitch conditioning, seamlessly. Its a multipurpose power that combines versatility, stability and longevity to help you stay locked in on the physical task at hand.",
        cost: 70,
        img: 'https://rebrand.ly/1i4khmw',
        category: 'shoes'
    },
    {
        name: 'Hex Slides',
        color: 'white',
        size: '9',
        gender: 'women',
        forkids: false,
        details: "Go beyond the flip-flop in these modern slides. Featuring a molded foam footbed with a squared-off toe, it's an instant warm-weather favorite.",
        cost: 35,
        img: 'https://rebrand.ly/mfd8obq',
        category: 'shoes'
    },
    {
        name: 'Sophia Jordan Slides',
        color: 'light pink',
        size: '9',
        gender: 'women',
        forkids: false,
        details: "Plush comfort is a must for your wardrobe—and footwear is no exception. These luxe slides have pillowy, criss-cross straps lined with fabric that feels soft against your skin. Air cushioning and a slight platform give you that 'walking on clouds' feel with every step.",
        cost: 85,
        img: 'https://rebrand.ly/11by5zs',
        category: 'shoes'
    },
    // KIDS (WOMEN)
    {
        name: 'Jumper-Wk',
        color: 'white/ice blue',
        size: '6',
        gender: 'women',
        forkids: true,
        details: "Honor Jordan's first 3 championships with a pair of kicks that collects details from each respective year's shoe and collages them together into one fire homage.",
        cost: 135,
        img: 'http://tiny.cc/v4aivz',
        category: 'shoes'
    },
    {
        name: 'Fly-HI 4',
        color: 'white/gold/black',
        size: '6',
        gender: 'women',
        forkids: true,
        details: "A sneaker that brings a classic performance look to streetwear. It features premium leather structured around an internal sleeve for a secure fit that's easy to get on and off. A heel Air unit and long-lasting foam combine for soft underfoot cushioning.",
        cost: 100,
        img: 'http://tiny.cc/05aivz',
        category: 'shoes'
    },
    {
        name: 'Mid-A 1',
        color: 'purple/white',
        size: '6',
        gender: 'women',
        forkids: true,
        details: "Premium materials, soft cushioning and a padded ankle collar offer total support and celebrate the shoe that started it all.",
        cost: 110,
        img: 'http://tiny.cc/c5aivz',
        category: 'shoes'
    },

    // ACCESSORIES *********************************************************************************************
    // MEN
    {
        name: 'FastX Sport Socks',
        color: 'white',
        size: '11',
        gender: 'men',
        forkids: false,
        details: "Your go-to for all-day comfort and performance. Crafted with quality materials, these socks offer a snug fit and excellent breathability. Whether you're hitting the gym or just taking it easy, step into comfort with Nike.",
        cost: 20,
        img: 'https://shorturl.at/fAV89',
        category: 'accessories'
    },
    {
        name: 'DistanceX Track Socks',
        color: 'black',
        size: '11',
        gender: 'men',
        forkids: false,
        details: "Your perfect companion for the track or trail. Engineered for performance, these socks provide a secure fit, superior breathability, and the comfort you need mile after mile. Step into the perfect stride with Nike Running Socks.",
        cost: 25,
        img: 'https://shorturl.at/bkDMY',
        category: 'accessories'
    },
    {
        name: 'FlashX Daily Socks',
        color: 'red',
        size: '11',
        gender: 'men',
        forkids: false,
        details: "Step up your style with the perfect blend of comfort and trendiness. Elevate every step with these stylish all-wear socks.",
        cost: 20,
        img: 'https://shorturl.at/ehNY8',
        category: 'accessories'
    },
    {
        name: 'StyleX Designer Socks',
        color: 'grey/design',
        size: '11',
        gender: 'men',
        forkids: false,
        details: "Where comfort and style collide. Step into effortless fashion with these socks featuring a trendy print, adding flair to your everyday look.",
        cost: 30,
        img: 'https://shorturl.at/vFY15',
        category: 'accessories'
    },
    {
        name: 'SO-X Everyday Backpack',
        color: 'pink/beige',
        size: '30L',
        gender: 'men',
        forkids: false,
        details: "A perfect blend of fashion and function. Elevate your everyday with this sleek and stylish backpack designed for comfort and confidence.",
        cost: 200,
        img: 'https://shorturl.at/svLR1',
        category: 'accessories'
    },
    {
        name: 'NewYork-X Street Backpack',
        color: 'black',
        size: '25L',
        gender: 'men',
        forkids: false,
        details: "A perfect fusion of style and practicality for your everyday adventures. Stay on-the-go with this sleek and comfortable backpack, designed to elevate your confidence on the go.",
        cost: 150,
        img: 'https://shorturl.at/sDEGW',
        category: 'accessories'
    },
    {
        name: 'Train-X Gym Duffel Bag',
        color: 'red',
        size: '100L',
        gender: 'men',
        forkids: false,
        details: "Your versatile companion for workouts and more. Designed for practicality and style, this duffel is perfect for all your training essentials. Elevate your fitness routine with Nike's functional and stylish training duffel.",
        cost: 250,
        img: 'https://shorturl.at/dyFIL',
        category: 'accessories'
    },
    {
        name: 'Classic Daily Hat',
        color: 'white',
        size: '10in',
        gender: 'men',
        forkids: false,
        details: "A timeless blend of simplicity and comfort. Elevate your look with this iconic hat, featuring the signature Nike logo. ",
        cost: 25,
        img: 'https://shorturl.at/oCMV3',
        category: 'accessories'
    },
    {
        name: 'Cream-E Beanie',
        color: 'cream',
        size: '10in',
        gender: 'men',
        forkids: false,
        details: "A perfect mix of warmth and style. Stay snug and stylish with this versatile beanie",
        cost: 30,
        img: 'https://shorturl.at/tvDI0',
        category: 'accessories'
    },
    {
        name: 'Street-E Beanie',
        color: 'black',
        size: '10in',
        gender: 'men',
        forkids: false,
        details: "Where comfort meets street style. Stay cozy and chic with this versatile knit. A perfect option for both chilly days and making a fashion statement.",
        cost: 25,
        img: 'https://rb.gy/yliutw',
        category: 'accessories'
    },
    {
        name: 'Sleek-G Sunglasses',
        color: 'green',
        size: 'Adjustable',
        gender: 'men',
        forkids: false,
        details: "Elevate your game with these sleek shades, designed for peak vision and cool comfort. Whether you're on the field or outdoors, stay focused with iconic Nike style.",
        cost: 150,
        img: 'https://shorturl.at/ijsAV',
        category: 'accessories'
    },
    {
        name: 'Matrix-G Sunglasses',
        color: 'black',
        size: 'Adjustable',
        gender: 'men',
        forkids: false,
        details: "Escape the matrix in bold style. Crafted for urban edge, these sunglasses elevate your look with a modern flair. Wherever you go, stand out with confidence.",
        cost: 100,
        img: 'https://shorturl.at/dlsKW',
        category: 'accessories'
    },
    {
        name: 'Icey-G Sunglasses',
        color: 'black/blue',
        size: 'Adjustable',
        gender: 'men',
        forkids: false,
        details: "Modern flair, instant cool. Elevate your look with vivid clarity with these polarized lenses. Ideal for urban adventures, these shades seamlessly combine fashion and function so you can stand out confidently",
        cost: 200,
        img: 'https://shorturl.at/eBP01',
        category: 'accessories'
    },
    {
        name: 'All-Catch Football Gloves',
        color: 'black',
        size: '10in',
        gender: 'men',
        forkids: false,
        details: "A winning combination of performance and style. Elevate your game with these sporty gloves, designed for a superior grip and comfort on the field. Dominate the game with the iconic Nike touch.",
        cost: 60,
        img: 'https://shorturl.at/jptwK',
        category: 'accessories'
    },
    // KIDS (MEN)
    {
        name: 'Element Backpack',
        color: 'black',
        size: '20L',
        gender: 'men',
        forkids: true,
        details: "Whether it's rushing to class or hanging out after school with friends, this backpack has the space to tackle it all. This bag features a large side pocket for water bottles as well as a front pocket to store quick-grab items.",
        cost: 50,
        img: 'https://shorturl.at/ceKO7',
        category: 'accessories'
    },
    {
        name: 'Goalie Gloves',
        color: 'black',
        size: '7',
        gender: 'men',
        forkids: true,
        details: "These gloves are ready to make every save! Soft padding provides cushioning against shots, while a smooth surface gives you grip in wet or dry conditions.",
        cost: 20,
        img: 'http://tiny.cc/t5aivz',
        category: 'accessories'
    },
    {
        name: 'J-Hooper Hat',
        color: 'black',
        size: '20in',
        gender: 'men',
        forkids: true,
        details: "made with heavy twill fabric in a classic 6-panel design that's comfortable for everyday wear. An adjustable strap at the back lets you customize the fit.",
        cost: 30,
        img: 'https://shorturl.at/fxNO8',
        category: 'accessories'
    },

    // WOMEN
    {
        name: 'Cherry Sports Socks',
        color: 'pink',
        size: '9',
        gender: 'women',
        forkids: false,
        details: "A true hybrid of style and comfort, the Nike Everyday Plus Crew Socks are cushioned in key areas to keep you comfortable throughout the day.",
        cost: 20,
        img: 'https://shorturl.at/kpxz8',
        category: 'accessories'
    },
    {
        name: '80s Ribbed Socks',
        color: 'beige',
        size: '9',
        gender: 'women',
        forkids: false,
        details: "Who doesn't love the socks of the '80s and '90s? While you don't have to wear the same pairs from back then, you can certainly wear the pair inspired by them.",
        cost: 15,
        img: 'https://shorturl.at/nADH6',
        category: 'accessories'
    },
    {
        name: 'Outdoorsy Day Socks',
        color: 'grey',
        size: '9',
        gender: 'women',
        forkids: false,
        details: "As outdoorsy as the Nike Everyday Plus Cushioned ankle socks look, they're actually just big softies. Their heathered, knit construction offers a trail-ready look and extra-cozy feel",
        cost: 20,
        img: 'http://tiny.cc/rp9ivz',
        category: 'accessories'
    },
    {
        name: 'Fluffy n` Fauxy Hat',
        color: 'beige',
        size: '10in',
        gender: 'women',
        forkids: false,
        details: "Welcome this fluffy faux fur Nike Apex Bucket into your lineup when you need some extra style. The mid-depth design features a large Swoosh logo on the front panel for a Nike finish.",
        cost: 40,
        img: 'http://tiny.cc/zp9ivz',
        category: 'accessories'
    },
    {
        name: 'Dry-FIT Casual Hat',
        color: 'pink',
        size: '10in',
        gender: 'women',
        forkids: false,
        details: "Open the doors for the Club Cap. The structured, mid-depth crown keeps you feeling comfortable and secure.",
        cost: 20,
        img: 'http://tiny.cc/cq9ivz',
        category: 'accessories'
    },
    {
        name: 'Mountain Peakin` Beanie',
        color: 'yellow',
        size: 'adjustable',
        gender: 'women',
        forkids: false,
        details: "Crafted for warmth, comfort and style, our Nike Peak beanie brings the goods for any cool weather outing.",
        cost: 20,
        img: 'http://tiny.cc/jq9ivz',
        category: 'accessories'
    },
    {
        name: 'Dry-ACE Visor Hat',
        color: 'white',
        size: '10in',
        gender: 'women',
        forkids: false,
        details: "This unstructured low-depth visor is made for tennis lovers both on and off the court. Ventilation in the design provides a breezy feel where you need it most, while the stretchy, sweat-wicking fabric helps you stay fresh.",
        cost: 25,
        img: 'http://tiny.cc/oq9ivz',
        category: 'accessories'
    },
    {
        name: 'Swerve-X Shades',
        color: 'black',
        size: 'adjustable',
        gender: 'women',
        forkids: false,
        details: "Meet the go-to pair for anywhere the sunny day takes you. With a slim profile that provides comfort while maintaining a stylish look.",
        cost: 110,
        img: 'http://tiny.cc/uq9ivz',
        category: 'accessories'
    },
    {
        name: 'Echo-X Shades',
        color: 'orange/pink',
        size: 'adjustable',
        gender: 'women',
        forkids: false,
        details: "Lightweight construction pairs with a minimalist top bar design frame to bring you the ultimate mirrored sunglasses.",
        cost: 120,
        img: 'http://tiny.cc/zq9ivz',
        category: 'accessories'
    },
    {
        name: 'Morpheus 2 Shades',
        color: 'black/green',
        size: 'adjustable',
        gender: 'women',
        forkids: false,
        details: "Meet the go-to pair for anywhere the sunny day takes you. With a slim profile that provides comfort while maintaining a stylish look.",
        cost: 110,
        img: 'http://tiny.cc/xq9ivz',
        category: 'accessories'
    },
    {
        name: 'Grand-Matrix 5 Shades',
        color: 'black',
        size: 'adjustable',
        gender: 'women',
        forkids: false,
        details: "Equally stylish as they are comfortable. These shades are vintage-inspired in looks with an oversized, rounded shape and built for ease with softly rubberized and adjustable temple tips that bend for effortless adjustability.",
        cost: 145,
        img: 'http://tiny.cc/5r9ivz',
        category: 'accessories'
    },
    {
        name: 'Audacity-O Shades',
        color: 'black',
        size: 'adjustable',
        gender: 'women',
        forkids: false,
        details: "Glam meets function. Whether you're brunching with besties or breaking a sweat on a sunny day, throw on your new favorite pair of shades.",
        cost: 110,
        img: 'http://tiny.cc/cr9ivz',
        category: 'accessories'
    },
    {
        name: 'Futori Everyday Bag',
        color: 'black',
        size: '1L',
        gender: 'women',
        forkids: false,
        details: "Snag the crossbody that's as useful as it is touchable. The main compartment features a zippered interior mesh pocket to keep your essentials organized.",
        cost: 50,
        img: 'http://tiny.cc/ir9ivz',
        category: 'accessories'
    },
    {
        name: 'Brasili Bag',
        color: 'black/white',
        size: '25L',
        gender: 'women',
        forkids: false,
        details: "ith plenty of space for your go-to workout needs, the Nike Brasilia Duffel is small but mighty. Its organizational capacity shows with the side and front zippered pockets to keep small gear in check.",
        cost: 35,
        img: 'http://tiny.cc/lr9ivz',
        category: 'accessories'
    },
    {
        name: 'On-GO Sporty Bag',
        color: 'forest green',
        size: '30L',
        gender: 'women',
        forkids: false,
        details: "Snag the bag that's as tough as it is spacious. The cord handles wrap around the zippered main compartment, which is large enough to hold your laptop and your water bottle.",
        cost: 40,
        img: 'http://tiny.cc/rr9ivz',
        category: 'accessories'
    },
    // KIDS (WOMEN)
    {
        name: 'GO Girly Sport Bag',
        color: 'pink',
        size: '20L',
        gender: 'women',
        forkids: true,
        details: "Whether it's rushing to class or hanging out after school with friends, this backpack has the space to tackle it all. This bag features a large side pocket for water bottles as well as a front pocket to store quick-grab items. Adjustable padded straps make wearing this bag comfortable and easy.",
        cost: 35,
        img: 'https://shorturl.at/jmoKU',
        category: 'accessories'
    },
    {
        name: 'GO-GO Sporty Bag',
        color: 'black',
        size: '1L',
        gender: 'women',
        forkids: true,
        details: "A small but mighty bag, and just the bag for wherever your day takes you! Perfect for hanging out with friends or adventuring around town, this bag features a spacious double-zippered main compartment for the essentials and a smaller front pocket for the small stuff that you need to grab quickly.",
        cost: 30,
        img: 'https://shorturl.at/sRWY0',
        category: 'accessories'
    },
    {
        name: 'Sporty Girl Hat',
        color: 'pink',
        size: '18in',
        gender: 'women',
        forkids: true,
        details: "A classic look with an adjustable back strap so it always fits just right.",
        cost: 15,
        img: 'http://tiny.cc/k6aivz',
        category: 'accessories'
    },
];

module.exports = products;